cabal-version: 3.0
name: openscad
version: 0.2.0.0
license: BSD-3-Clause
license-file: LICENSE
author: Michael Bock
maintainer: no-day@posteo.net
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

common extensions
  default-extensions:
    DuplicateRecordFields
    FlexibleInstances
    LambdaCase
    NamedFieldPuns
    NoFieldSelectors

  default-language: Haskell2010

library
  import: warnings, extensions
  exposed-modules: OpenSCAD.Model
  other-modules:
    OpenSCAD.Optimizer
    OpenSCAD.Raw

  hs-source-dirs: lib
  build-depends: base ^>=4.17.2.1
